title: Ikenna M. D. Nwankwo
logo: /assets/head_shot.png
description: â€” Portfolio: Showcasing Data Analytics, Research, and Business Strategy Projects.
#show_downloads: true
theme: jekyll-theme-minimal
url: "https://nmartin169.github.io"
baseurl: "/webportfolio"
