title: Ikenna M. D. Nwankwo â€” Portfolio
logo: /assets/head_shot.png
description: Showcasing Data Analytics, Research, and Business Strategy Projects.
#show_downloads: true
theme: jekyll-theme-minimal
url: "https://nmartin169.github.io"
baseurl: "/webportfolio"
